/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Trading Robot Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HealthStatus,
  ListStrategiesParams,
  MarketStats,
  PerformancePoint,
  Strategy,
  StrategyDetail,
  StrategyInput,
  StrategyListResponse,
  TradeHistory,
  DeployResult,
  DeployUploadResult,
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListStrategiesUrl = (params?: ListStrategiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/strategies?${stringifiedParams}` : `/api/strategies`
}

/**
 * Returns all available copy trading strategies
 * @summary List all strategies
 */
export const listStrategies = async (params?: ListStrategiesParams, options?: RequestInit): Promise<StrategyListResponse> => {

  return customFetch<StrategyListResponse>(getListStrategiesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStrategiesQueryKey = (params?: ListStrategiesParams,) => {
    return [
    `/api/strategies`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStrategiesQueryOptions = <TData = Awaited<ReturnType<typeof listStrategies>>, TError = ErrorType<unknown>>(params?: ListStrategiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listStrategies>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStrategiesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStrategies>>> = ({ signal }) => listStrategies(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStrategies>>, TError, TData> & { queryKey: QueryKey }
}

export type ListStrategiesQueryResult = NonNullable<Awaited<ReturnType<typeof listStrategies>>>
export type ListStrategiesQueryError = ErrorType<unknown>


/**
 * @summary List all strategies
 */

export function useListStrategies<TData = Awaited<ReturnType<typeof listStrategies>>, TError = ErrorType<unknown>>(
 params?: ListStrategiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listStrategies>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListStrategiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateStrategyUrl = () => {




  return `/api/strategies`
}

/**
 * @summary Create a new strategy
 */
export const createStrategy = async (strategyInput: StrategyInput, options?: RequestInit): Promise<Strategy> => {

  return customFetch<Strategy>(getCreateStrategyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      strategyInput,)
  }
);}




export const getCreateStrategyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStrategy>>, TError,{data: BodyType<StrategyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createStrategy>>, TError,{data: BodyType<StrategyInput>}, TContext> => {

const mutationKey = ['createStrategy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStrategy>>, {data: BodyType<StrategyInput>}> = (props) => {
          const {data} = props ?? {};

          return  createStrategy(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateStrategyMutationResult = NonNullable<Awaited<ReturnType<typeof createStrategy>>>
    export type CreateStrategyMutationBody = BodyType<StrategyInput>
    export type CreateStrategyMutationError = ErrorType<unknown>

    /**
 * @summary Create a new strategy
 */
export const useCreateStrategy = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStrategy>>, TError,{data: BodyType<StrategyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createStrategy>>,
        TError,
        {data: BodyType<StrategyInput>},
        TContext
      > => {
      return useMutation(getCreateStrategyMutationOptions(options));
    }

export const getGetStrategyUrl = (id: number,) => {




  return `/api/strategies/${id}`
}

/**
 * @summary Get strategy details
 */
export const getStrategy = async (id: number, options?: RequestInit): Promise<StrategyDetail> => {

  return customFetch<StrategyDetail>(getGetStrategyUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStrategyQueryKey = (id: number,) => {
    return [
    `/api/strategies/${id}`
    ] as const;
    }


export const getGetStrategyQueryOptions = <TData = Awaited<ReturnType<typeof getStrategy>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStrategy>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStrategyQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStrategy>>> = ({ signal }) => getStrategy(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStrategy>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStrategyQueryResult = NonNullable<Awaited<ReturnType<typeof getStrategy>>>
export type GetStrategyQueryError = ErrorType<void>


/**
 * @summary Get strategy details
 */

export function useGetStrategy<TData = Awaited<ReturnType<typeof getStrategy>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStrategy>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStrategyQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetStrategyPerformanceUrl = (id: number,) => {




  return `/api/strategies/${id}/performance`
}

/**
 * @summary Get performance chart data for a strategy
 */
export const getStrategyPerformance = async (id: number, options?: RequestInit): Promise<PerformancePoint[]> => {

  return customFetch<PerformancePoint[]>(getGetStrategyPerformanceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStrategyPerformanceQueryKey = (id: number,) => {
    return [
    `/api/strategies/${id}/performance`
    ] as const;
    }


export const getGetStrategyPerformanceQueryOptions = <TData = Awaited<ReturnType<typeof getStrategyPerformance>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStrategyPerformance>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStrategyPerformanceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStrategyPerformance>>> = ({ signal }) => getStrategyPerformance(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStrategyPerformance>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStrategyPerformanceQueryResult = NonNullable<Awaited<ReturnType<typeof getStrategyPerformance>>>
export type GetStrategyPerformanceQueryError = ErrorType<unknown>


/**
 * @summary Get performance chart data for a strategy
 */

export function useGetStrategyPerformance<TData = Awaited<ReturnType<typeof getStrategyPerformance>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStrategyPerformance>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStrategyPerformanceQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListStrategyTradesUrl = (id: number,) => {




  return `/api/strategies/${id}/trades`
}

/**
 * @summary Get trade history for a strategy
 */
export const listStrategyTrades = async (id: number, options?: RequestInit): Promise<TradeHistory> => {

  return customFetch<TradeHistory>(getListStrategyTradesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStrategyTradesQueryKey = (id: number,) => {
    return [
    `/api/strategies/${id}/trades`
    ] as const;
    }


export const getListStrategyTradesQueryOptions = <TData = Awaited<ReturnType<typeof listStrategyTrades>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listStrategyTrades>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStrategyTradesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStrategyTrades>>> = ({ signal }) => listStrategyTrades(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStrategyTrades>>, TError, TData> & { queryKey: QueryKey }
}

export type ListStrategyTradesQueryResult = NonNullable<Awaited<ReturnType<typeof listStrategyTrades>>>
export type ListStrategyTradesQueryError = ErrorType<unknown>


/**
 * @summary Get trade history for a strategy
 */

export function useListStrategyTrades<TData = Awaited<ReturnType<typeof listStrategyTrades>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listStrategyTrades>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListStrategyTradesQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMarketStatsUrl = () => {




  return `/api/stats`
}

/**
 * @summary Get overall marketplace statistics
 */
export const getMarketStats = async ( options?: RequestInit): Promise<MarketStats> => {

  return customFetch<MarketStats>(getGetMarketStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMarketStatsQueryKey = () => {
    return [
    `/api/stats`
    ] as const;
    }


export const getGetMarketStatsQueryOptions = <TData = Awaited<ReturnType<typeof getMarketStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMarketStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMarketStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketStats>>> = ({ signal }) => getMarketStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMarketStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMarketStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getMarketStats>>>
export type GetMarketStatsQueryError = ErrorType<unknown>


/**
 * @summary Get overall marketplace statistics
 */

export function useGetMarketStats<TData = Awaited<ReturnType<typeof getMarketStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMarketStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMarketStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}


// ═══════════════════════════════════════════════════════════════════
// Deploy endpoints
// ═══════════════════════════════════════════════════════════════════

export const getDeployLaunchUrl = (id: number) => `/api/strategies/${id}/deploy/launch`;

export const deployLaunch = async (
  id: number,
  form: { mt_version: number; account_login: string; account_password: string; account_server: string; trade_symbol: string; trade_period: string; terminal_path: string },
): Promise<DeployResult> => {
  const fd = new FormData();
  fd.append('mt_version', String(form.mt_version));
  fd.append('account_login', form.account_login);
  fd.append('account_password', form.account_password);
  fd.append('account_server', form.account_server);
  fd.append('trade_symbol', form.trade_symbol);
  fd.append('trade_period', form.trade_period);
  fd.append('terminal_path', form.terminal_path);
  return customFetch<DeployResult>(getDeployLaunchUrl(id), { method: 'POST', body: fd });
};

export const getDeployFullUrl = (id: number) => `/api/strategies/${id}/deploy`;

export const deployFull = async (
  id: number,
  form: { mt_version: number; url: string; account_login: string; account_password: string; account_server: string; trade_symbol: string; trade_period: string; terminal_path: string },
): Promise<DeployResult> => {
  const fd = new FormData();
  fd.append('mt_version', String(form.mt_version));
  fd.append('url', form.url);
  fd.append('account_login', form.account_login);
  fd.append('account_password', form.account_password);
  fd.append('account_server', form.account_server);
  fd.append('trade_symbol', form.trade_symbol);
  fd.append('trade_period', form.trade_period);
  fd.append('terminal_path', form.terminal_path);
  return customFetch<DeployResult>(getDeployFullUrl(id), { method: 'POST', body: fd });
};

export const getDeployUploadUrl = (id: number) => `/api/strategies/${id}/deploy/upload`;

export const deployUploadFile = async (
  id: number,
  file: File,
  mt_version: number,
  account_login: string,
  account_password: string,
  account_server: string,
  trade_symbol: string,
  trade_period: string,
  terminal_path: string,
): Promise<DeployUploadResult> => {
  const fd = new FormData();
  fd.append('file', file);
  fd.append('mt_version', String(mt_version));
  fd.append('account_login', account_login);
  fd.append('account_password', account_password);
  fd.append('account_server', account_server);
  fd.append('trade_symbol', trade_symbol);
  fd.append('trade_period', trade_period);
  fd.append('terminal_path', terminal_path);
  return customFetch<DeployUploadResult>(getDeployUploadUrl(id), { method: 'POST', body: fd });
};

export const getStrategyDeployLaunchMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(
  id: number,
  options?: { mutation?: UseMutationOptions<DeployResult, TError, { form: Parameters<typeof deployLaunch>[1] }, TContext> },
) => {
  const mutationKey = ['deployLaunch', id];
  const { mutation: mutationOptions } = options ?? { mutation: { mutationKey } };
  const mutationFn: MutationFunction<DeployResult, { form: Parameters<typeof deployLaunch>[1] }> = (props) =>
    deployLaunch(id, props.form);
  return { mutationFn, mutationKey: mutationKey, ...mutationOptions };
};

export const getStrategyDeployFullMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(
  id: number,
  options?: { mutation?: UseMutationOptions<DeployResult, TError, { form: Parameters<typeof deployFull>[1] }, TContext> },
) => {
  const mutationKey = ['deployFull', id];
  const { mutation: mutationOptions } = options ?? { mutation: { mutationKey } };
  const mutationFn: MutationFunction<DeployResult, { form: Parameters<typeof deployFull>[1] }> = (props) =>
    deployFull(id, props.form);
  return { mutationFn, mutationKey: mutationKey, ...mutationOptions };
};







