/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Trading Robot Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Strategy {
  id: number;
  name: string;
  /** @nullable */
  logoUrl?: string | null;
  growthPercent: number;
  minInvest: number;
  investors: number;
  totalFunds: number;
  days: number;
  performanceFee: number;
  chartPoints?: number[];
}

export interface StrategyDetail {
  id: number;
  name: string;
  /** @nullable */
  logoUrl?: string | null;
  growthPercent: number;
  minInvest: number;
  investors: number;
  totalFunds: number;
  days: number;
  drawdown: number;
  withdrawalPolicy: string;
  passwordProtected: boolean;
  availability: string;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  userAccount?: string | null;
  /** @nullable */
  tradesHistoryFrom?: string | null;
  /** @nullable */
  description?: string | null;
  performanceFeeEnabled: boolean;
  performanceFee: number;
  performanceAgentFee: number;
  entryFeeEnabled: boolean;
  entryFee: number;
  entryAgentFee: number;
  subscriptionFeeEnabled: boolean;
  subscriptionFeeType: string;
  subscriptionFee: number;
  subscriptionAgentFee: number;
}

export interface StrategyInput {
  name: string;
  minInvest: number;
  withdrawalPolicy: string;
  passwordProtected?: boolean;
  password?: string | null;
  availability: string;
  userName?: string | null;
  userAccount?: string | null;
  tradesHistoryFrom?: string | null;
  description?: string | null;
  performanceFeeEnabled: boolean;
  performanceFee: number;
  performanceAgentFee: number;
  entryFeeEnabled: boolean;
  entryFee: number;
  entryAgentFee: number;
  subscriptionFeeEnabled: boolean;
  subscriptionFeeType: string;
  subscriptionFee: number;
  subscriptionAgentFee: number;
}

export interface PerformancePoint {
  date: string;
  value: number;
}

export interface Trade {
  id: number;
  instrument: string;
  openTime: string;
  openPrice: number;
  closeTime: string;
  closePrice: number;
  tradeType: string;
  volume: number;
  profit: number;
}

export interface TradeHistory {
  trades: Trade[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface StrategyListResponse {
  strategies: Strategy[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface MarketStats {
  totalStrategies: number;
  totalInvestors: number;
  totalFunds: number;
  topGrowth: number;
}

export type ListStrategiesParams = {
search?: string;
sortBy?: string;
order?: string;
page?: number;
pageSize?: number;
};

export interface DeployStep {
  step: string;
  status: string;
  detail?: string;
  robot?: string;
  expert?: string;
  preset?: string;
  path?: string;
  terminal?: string;
}

export interface DeployResult {
  steps: DeployStep[];
  status: string;
}

export interface DeployUploadResult {
  status: string;
  filename: string;
  path: string;
}

